import fs from 'fs';
import path from 'path';
import { PDFDocument, StandardFonts } from 'pdf-lib';
const D = import.meta.dirname;
const doc = await PDFDocument.load(fs.readFileSync(path.join(D, 'out_form.pdf')));
const page = doc.getPages()[0];
const png = await doc.embedPng(fs.readFileSync(path.join(D, 'sig.png')));
page.drawImage(png, { x: 300, y: 600, width: 160, height: 80, opacity: 0.95 });
// whiteout underneath first, then stamp (the "sign over a printed line" case)
page.drawRectangle({ x: 300, y: 600, width: 160, height: 80, color: undefined });
const out = await doc.save();
fs.writeFileSync(path.join(D, 'out_stamped.pdf'), out);
const re = await PDFDocument.load(out);
console.log('T4 stamped PDF bytes:', out.length, '| pages:', re.getPageCount(), '| fields still present:', re.getForm().getFields().length);
const f = re.getForm(); f.flatten();
const flat = await re.save();
fs.writeFileSync(path.join(D, 'out_flattened.pdf'), flat);
const re2 = await PDFDocument.load(flat);
console.log('T4 after flatten -> interactive fields remaining:', re2.getForm().getFields().length, '(0 = submit-proof)');
console.log('T4 flattened bytes:', flat.length);
